"""use_groupme

Revision ID: 0d455068c7eb
Revises: b3b03f4cb8bc
Create Date: 2019-07-31 20:25:34.766035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d455068c7eb'
down_revision = 'b3b03f4cb8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('group_id', sa.String(length=16), nullable=True),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bot_instance')
    op.add_column('user', sa.Column('access_token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_column('user', 'name')
    op.drop_column('user', 'access_token')
    op.create_table('bot_instance',
    sa.Column('group_id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bot_id', sa.VARCHAR(length=26), nullable=True),
    sa.Column('owner_id', sa.VARCHAR(length=16), nullable=True),
    sa.Column('owner_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=32), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('bot_id')
    )
    op.drop_table('instance')
    # ### end Alembic commands ###
