"""add prefix_filter

Revision ID: 29a41197e9a8
Revises: 421d05685948
Create Date: 2022-10-13 16:06:08.198730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a41197e9a8'
down_revision = '421d05685948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('prefix_filter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'prefix_filter')
    # ### end Alembic commands ###
