"""add has_user_token_access

Revision ID: 421d05685948
Revises: e71f3327b1ba
Create Date: 2020-09-07 13:05:05.797192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421d05685948'
down_revision = 'e71f3327b1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('has_user_token_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'has_user_token_access')
    # ### end Alembic commands ###
