"""empty message

Revision ID: 460febbda8b5
Revises: fec5e124e207
Create Date: 2019-09-20 21:07:19.524467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460febbda8b5'
down_revision = 'fec5e124e207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('website', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'website')
    # ### end Alembic commands ###
