"""add welcome_message

Revision ID: 738683b76d82
Revises: 002602fd57cb
Create Date: 2022-11-11 17:05:18.446734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738683b76d82'
down_revision = '002602fd57cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('welcome_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'welcome_message')
    # ### end Alembic commands ###
