"""empty message

Revision ID: 996092f93e2b
Revises: 470f93a9852a
Create Date: 2019-07-31 20:42:37.410083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996092f93e2b'
down_revision = '470f93a9852a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
