"""add_client_id

Revision ID: b3b03f4cb8bc
Revises: f0e523dacec3
Create Date: 2019-07-30 21:10:07.643518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b03f4cb8bc'
down_revision = 'f0e523dacec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('client_id', sa.String(length=48), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'client_id')
    # ### end Alembic commands ###
