"""empty message

Revision ID: e71f3327b1ba
Revises: 393eb0b01a27
Create Date: 2019-09-21 02:38:31.881221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71f3327b1ba'
down_revision = '393eb0b01a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('repo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'repo')
    # ### end Alembic commands ###
