"""empty message

Revision ID: fec5e124e207
Revises: 
Create Date: 2019-09-15 05:01:37.402207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec5e124e207'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('avatar', sa.String(length=45), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('name_customizable', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=70), nullable=True),
    sa.Column('avatar_url_customizable', sa.Boolean(), nullable=True),
    sa.Column('callback_url', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('token', sa.String(length=22), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('instance',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('group_id', sa.String(length=16), nullable=True),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.String(length=70), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance')
    op.drop_table('bot')
    op.drop_table('user')
    # ### end Alembic commands ###
